name: tafsir_albaqara
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_html: ^0.11.1
  dynamic_theme:
  shared_preferences: ^0.5.12+4
  bloc: ^4.0.0
  equatable: ^1.2.0
  flutter_bloc: ^4.0.0
  google_fonts_arabic: ^1.1.7
  google_fonts: ^1.1.0
  flutter_email_sender: ^3.0.1
  image_picker: ^0.6.7+4
  get_it: ^1.0.3+2
  url_launcher: ^5.7.10
  share: ^0.6.4+3
  store_redirect: ^1.0.2
  test: ^1.15.2
  bloc_test: ^5.0.0

dev_dependencies:
  import_sorter: ^4.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/content.json
